version: '3.9'

services:
  app:
    container_name: csharpapp
    image: emoshimo/employeemanagement:1.0
    build: .
    ports:
      - "8080:80"
    env_file:
      - .env
    environment:
      - ConnectionStrings__WebApiDatabase=Host=db;Database=postgres;Username=postgres;Password=123456
    depends_on:
      - db

  db:
    container_name: postgres_container
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data_emp:/var/lib/postgresql/data

volumes:
  postgres_data_emp:
    external: true
